### ISSUE TITLE
FullScreen Safari Extension

### ISSUE THREAD

**Issue by unCleanCode** [stefanvd/Browser-Extensions#1]
Could you upload source or a binary of FullScreen Safari extension?

I'm all the time using the Chrome version of this extension, but I more often use Safari browser so would be glad to get it on Safari

**Comment by stefanvd** [comment]
Hi there,

If you are using the previous Safari version, you can install the Full Screen Safari extension.
https://www.stefanvd.net/downloads/Full%20Screen.safariextz

If you still have this issue or need more help. Please use the support form https://www.stefanvd.net/support

Thanks,

**Comment by unCleanCode** [comment]
Thanks
Installed it with this manual: http://osxdaily.com/2019/02/08/bypass-safari-no-longer-supports-unsafe-extension-error-mac/
It seems to be loaded (content.js is loaded, icon is there, preferences are working)...but it doesn't fullscreen anything when I click on a button :(

**Comment by stefanvd** [comment]
What is the main goal you want to use this Full Screen Safari extension? I can make this Safari extension available in the Mac App Store. This week, If I know what are the important features you need.

**Comment by unCleanCode** [comment]
Wow, that would be wonderful!
I use it to fullscreen videos on sites like youtube, twitch and some other sites which are using HTML-based video players (I believe they are mostly based on video.js and JWPlayer)

**Comment by stefanvd** [comment]
I did the test and build. And Safari App extension doesn't allow the full screen API (web javascript code). And it asks "failed to execute 'requestfullscreen'" because it needs a user gesture (= a click of the mouse button). So to build the macOS app/Safari extension is not possible anymore because of Apple.

**Comment by verasitytech** [comment]
too bad :(
Can it request user's click? Like when there are 2 elements it asks to pick one with a click

Anyway - thanks for trying

**Comment by stefanvd** [comment]
The principle like the Full Screen Chrome extension doesn't work for Apple Safari (that go directly to full screen with one single click on the Full Screen button). I did the test with add a new button on the current web page, and then try to simulate the click: **document.getElementById("stefanvdfullscreen").click();** But that doesn't work. Only I as a real user must use my mouse and click on this new button. And then it brings the video/page to full screen. That idea you suggest can be good, but the user experience is different and not great.
