### ISSUE TITLE
Proper Menubar for Chrome browser?

### ISSUE THREAD

**Issue by paronos** [stefanvd/Browser-Extensions#2]
What happen to [Proper Menubar](https://www.stefanvd.net/project/proper-menubar/browser/index.htm) on the [Chrome WebStore](https://chrome.google.com/webstore/detail/proper-menubar-for-google/egclcjdpndeoioimlbbbmdhcaopnedkp?hl=en)?

![ProperMenu Chrome WebStore](https://user-images.githubusercontent.com/23290139/57914108-a2174a00-78c0-11e9-84b4-eda94adb6c65.png)

**Comment by stefanvd** [comment]
If you still have this issue or need more help. Please use the support form https://www.stefanvd.net/support

Thanks,
