### ISSUE TITLE
Problems viewing some pages.

### ISSUE THREAD

**Issue by Gunderyk** [stefanvd/Browser-Extensions#4]
Hello, welcome! First of all, I would like to thank you for your work and for a really good extension to the Chrome browser. 23 inch monitor, Full HD, 130% Windows zoom, 145% zoom in the browser, I have poor eyesight. However, I have some comments that I hope you will include and help. I am a disabled person and for me a decent zoom is the basis of web browsing. A few of my comments: on this page -https: //www.gov.pl/web/koronavirus/wykaz-zarazen-koronavirus-sars-cov-2- you cannot set the zoom larger than 115%, because the page is displayed incorrectly. In addition, pages for example -https: //www.interia.pl/-, -https: //www.onet.pl/- and many others are displayed with a 1-second delay, which is not in this extension -Zoom Page WE -. pages are displayed immediately. I definitely prefer your extension because it has more options and you are constantly developing them. If you could eliminate the page enlargement message because it can't be turned off in the browser that displays every time we open the page or refresh it, it's really annoying. In the old extension - NoSquint Plus - which is no longer in the - chrome web store - the message was displayed only once, at the first opening of the page, but later fortunately not, so I think that it can be eliminated, although I must admit that I am a layman , so I do not know. :). At -https: //www.google.com/-, it's difficult to set, for example, a 120% magnification that suits me, you have to do it several times because I don't want to remember a specific magnification. On this also -https: //www.gov.pl/web/koronavirus/wykaz-zarazen-koronavirus-sars-cov-2- I do not know if this happens only with me .. Could you take into account my comments and possibly improve your addition to make everything work properly. Sorry for my English, I use a translator :) I cordially greet you and look forward to your reply.
Gunderic

**Comment by stefanvd** [comment]
This is not a support forum here. But a place to report a bug. Please use next time the support form if you need any help. You can find it on this page: [https://www.stefanvd.net/support](https://www.stefanvd.net/support)

If you experience an incorrect zoom scale view, try to change the zooming engine from CSS to browser built-in engine (in the Zoom Chrome extension Options page). That should solve this problem.

Thanks,
